---
abstract: 'A complete SPARQL 1.1 Query and Update implementation for use with RDF::Trine.'
author:
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  FindBin: 0
  Test::Exception: 0
  Test::JSON: 0
  Test::More: 0.88
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Query
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  Geo::Distance: 0.09
  Getopt::Simple: 0
  LWP::Simple: 0
requires:
  Data::UUID: 0
  DateTime::Format::W3CDTF: 0
  Digest::SHA: 0
  Error: 0
  File::Spec: 0
  File::Temp: 0
  I18N::LangTags: 0
  JSON: 2
  Module::Pluggable: 0
  Parse::RecDescent: 0
  RDF::Trine: 1.003
  Scalar::Util: 0
  Set::Scalar: 0
  URI: 1.52
resources:
  bugtracker: https://github.com/kasei/perlrdf/issues
  homepage: http://search.cpan.org/dist/RDF-Query/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kasei/perlrdf/
version: 2.910_01
