# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RDF-Query
version:      1.012
version_from: lib/RDF/Query.pm
installdirs:  site
requires:
    LWP::Simple:                   0
    Parse::RecDescent:             0
    RDF::Core:                     0
    RDF::Redland:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
