abstract: A pure-perl impelmentation of the RDF query languages SPARQL and RDQL.
author: 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::JSON: 0
  Test::More: 0.61
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
module_name: RDF::Query
name: RDF-Query
no_index:
  directory:
    - inc
    - t
recommends:
  LWP::Simple: 0
  RDF::Redland: 1
requires:
  DateTime::Format::W3CDTF: 0
  Error: 0
  JSON: 0
  Parse::RecDescent: 0
  RDF::Core: 0
  Scalar::Util: 0
  Storable: 0
version: 1.039
