--- #YAML:1.0
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
name: RDF-Query
version: 2.000_05
abstract: A pure-perl impelmentation of the RDF query languages SPARQL and RDQL.
author:
  - Gregory Todd Williams <gwilliams@cpan.org>
build_requires:
  Test::Exception: 0
  Test::JSON: 0
  Test::More: 0.61
  YAML: 0
  FindBin: 0
distribution_type: module
generated_by: Module::Install version 0.63
license: perl
no_index:
  directory:
    - inc
    - t
recommends:
  RDF::Redland: 1
  RDF::Core: 0
  JavaScript: 0
  Geo::Distance: 0.09
requires:
  Digest::SHA1: 0
  LWP::Simple: 0
  DateTime::Format::W3CDTF: 0
  Error: 0
  I18N::LangTags: 0
  JSON: 2
  Parse::RecDescent: 0
  Scalar::Util: 0
  Storable: 0
  URI: 0
  List::MoreUtils: 0
  Set::Scalar: 0
  RDF::Trine: 0.104
resources:
  homepage: http://kasei.us/code/rdf-query/
  Repository: http://code.google.com/p/perlrdf/source
